# Generated by Django 5.1.2 on 2025-06-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caloriegoal",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="caloriegoal",
            name="height",
            field=models.FloatField(default=0, help_text="In centimeters"),
        ),
        migrations.AlterField(
            model_name="caloriegoal",
            name="weight",
            field=models.FloatField(default=0, help_text="In kilograms"),
        ),
    ]
